# server {
#   listen 80;

#   server_name _;

#   root /usr/share/nginx/html;
#   index index.html;

#   location / {
#     try_files $uri /index.html;
#   }

#   location /api/ {
#     proxy_pass http://backend:5000/;
#     proxy_set_header Host $host;
#     proxy_set_header X-Real-IP $remote_addr;
#   }
# }


server {
    listen 80;
    server_name docker-2.duckdns.org;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    server_name docker-2.duckdns.org;

    ssl_certificate /etc/ssl/fullchain.pem;
    ssl_certificate_key /etc/ssl/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://backend:5000/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}